kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
workspace:
  base: /go
  path: src/github.com/tsjnsn/kt

steps:
  - name: build-linux
    group: build
    image: golang
    volumes:
      - name: target
        path: /go/target
    commands:
      - go get
      - go build -o kt-linux -ldflags "-X main.buildTime=`date --iso-8601=s` -X main.buildVersion=`git rev-parse HEAD | cut -c-7`" .

  - name: build-darwin
    group: build
    image: golang
    volumes:
      - name: target
        path: /go/target
    environment: { GOOS: "darwin" }
    commands:
      - go get
      - go build -o kt-darwin -ldflags "-X main.buildTime=`date --iso-8601=s` -X main.buildVersion=`git rev-parse HEAD | cut -c-7`" .

  - name: publish
    image: socialengine/github-release
    environment:
      GITHUB_RELEASE_VERSION: v0.7.2
    commands:
      - "github-release release --user tsjnsn --repo kt --tag ${DRONE_TAG} --name ${DRONE_TAG}"
      - "github-release upload  --user tsjnsn --repo kt --tag ${DRONE_TAG} --name kt-linux --file ./kt-linux"
      - "github-release upload  --user tsjnsn --repo kt --tag ${DRONE_TAG} --name kt-darwin --file ./kt-darwin"
    secrets:
      - GITHUB_TOKEN
    when:
      event:
        - tag
